name: Automated/scheduled Workflow Sample

# Triggers the action as scheduled
on:
  # Runs on the 1st day of every month at 11:00 AM
  schedule:
    # Cron format:
    #   ┌───────────── minute (0 - 59)
    #   │ ┌───────────── hour (0 - 23)
    #   │ │ ┌───────────── day of the month (1 - 31)
    #   │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #   │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #   │ │ │ │ │                                   
    #   │ │ │ │ │
    #   │ │ │ │ │
    #   * * * * *
    # See: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron:  '0 11 1 * *'

# The scheduled workflow to run
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # A command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Creates a comment to an issue number 1 using github command.
    # See: https://github.com/actions/github-script
    - uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          github.issues.createComment({
            issue_number: 1,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Ping from github actons! (This is a scheduled comment)'
          })
