name: Automated/scheduled Workflow Sample

# Runs on every 15 minutes
on:
  schedule:
    - cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

# The scheduled workflow to run 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # A command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Creates a comment to an issue number 1 using github command.
    # See: https://github.com/actions/github-script
    - uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          github.issues.createComment({
            issue_number: 1,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Hello from github actons! (This is a scheduled comment)'
          })
